module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    fontFamily: {
      sans: [
        "Avenir",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      mono: [
        "IBM Plex Mono",
        "ui-monospace",
        "SFMono-Regular",
        "Menlo",
        "Monaco",
        "Consolas",
        "Liberation Mono",
        "Courier New",
        "monospace",
      ],
    },
    extend: {
      colors: {
        dark: "#171717",
        black: "#000000",
        white: "#FFFFFF",
        "code-background": "#20272C",
        "code-comments": "#C2CFE1",
        "code-primary": "#FF6CCD",
        "code-secondary": "#5BC4FF",
        "code-tertiary": "#5CE1B1",
        text: "#334155",
        "text-dark": "#C2CFE1",
        divider: "#4E5D72",
        "divider-dark": "#393741",
        primary: "#C854FF",
        button: "#94A3B8",
        "button-dark": "#20272C",
        icon: "#BFBFBF",
        search: "#F4F6F8",
      },
      fontSize: {
        header: "26.14px",
      },
      lineHeight: {
        header: "35.7px",
      },
      borderWidth: {
        button: "1.8px",
      },
      screens: {
        lg: "1120px",
        md: "940px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
